from random import randint

TOP_200 = ['Lexapro',
           'Vicodin',
           'Prinivil',
           'Qbrelis',
           'Zocor',
           'Synthroid',
           'Amoxil',
           'Trimox',
           'Zithromax',
           'Microzide',
           'Aquazide',
           'Norvasc',
           'Xanax',
           'Glucophage',
           'Lipitor',
           'Prilosec',
           'Cipro',
           'Proquin',
           'Zofran',
           'Clozaril',
           'Lasix',
           'Levitra',
           'Sumycin',
           'Ala-Tet',
           'Brodspec',
           'Heparin Sodium',
           'Valcyte',
           'Lamictal',
           'Diflucan',
           'Tenormin',
           'Singulair',
           'Flonase Nasal Spray',
           'Zyloprim',
           'Fosamax',
           'Pepcid',
           'Omnicef',
           'Yaz',
           'Apresoline',
           'Cogentin',
           'Tussionex PennKinetic',
           'Paxil',
           'Ativan',
           'Pyridium',
           'Plaquenil',
           'Lidoderm',
           'Cataflam',
           'Rayos',
           'Deltasone',
           'Zetia',
           'Evista',
           'Dilantin',
           'Lovaza',
           'Zanaflex',
           'Hytrin',
           'Dyrenium',
           'Altace',
           'Pravachol',
           'Risperdal',
           'Lunesta',
           'Celebrex',
           'Premarin',
           'Avelox',
           'Aricept',
           'Macrobid',
           'Macrodantin',
           'Duragesic Skin Patch',
           'Imdur',
           'Prozac',
           'Sarafem',
           'Aristocort',
           'Suboxone',
           'Vyvanse',
           'Pamelor',
           'HumaLOG',
           'Depacon',
           'Depakote',
           'BetaSept',
           'ChloraPrep',
           'Bentyl',
           'Imitrex',
           'Protonix',
           'Lopressor',
           'Robitussen',
           'Valium',
           'Viagra',
           'Bactroban',
           'Januvia',
           'Reglan',
           'Relafen',
           'Keflex',
           'Effexor',
           'Boniva',
           'Zantac',
           'Ex-Lax',
           'Senna Lax',
           'NovoLog',
           'Bayer',
           'Ecotrin',
           'Bufferin',
           'Lioresal',
           'Flagyl',
           'Keppra',
           'Colcrys',
           'Mitigare',
           'Zyprexa',
           'Avodart',
           'TriCor',
           'Antara',
           'Cardura',
           'Aleve',
           'Aldactone',
           'Namenda',
           'Methadose',
           'Vasotec',
           'Epaned',
           'Tamiflu',
           'Requip',
           'PC Pen VK',
           'Pen V',
           'Strattera',
           'Ambien',
           'Advair',
           'Levaquin',
           'Tofranil',
           'Reclast',
           'Zometa',
           'Glucotrol',
           'Constulose',
           'AcipHex',
           'Otrexup',
           'Cleocin',
           'Tylenol',
           'Feosol',
           'Relpax',
           'Carbacot',
           'Robaxin',
           'DiaBeta',
           'Celexa',
           'Benicar',
           'Coreg',
           'Spiriva',
           'Xolair',
           'NitroStat Sublingual',
           'Eliquis',
           'Neurontin',
           'Enbrel',
           'Herceptin',
           'Atripla',
           'Xarelto',
           'Stalevo 50',
           'Fioricet',
           'Levemir',
           'Lovenox',
           'Ritalin',
           'Concerta',
           'Crestor',
           'Xgeva',
           'Prolia',
           'Pradaxa',
           'Sensipar',
           'Vesicare',
           'Haldol',
           'Ala-Cort',
           'HumuLIN',
           'Isentress',
           'Stelara',
           'Mobic',
           'Remicade',
           'Night Time',
           'Renvela',
           'Fragmin',
           'Zoloft',
           'Klonopin',
           'Avalide',
           'Ceftin',
           'Nizoral Topical',
           'Lyrica',
           'Nexium',
           'Combivent Respimat',
           'Niaspan',
           'Uroxatral',
           'Biaxin',
           'Zomig',
           'Invokana',
           'Saxenda',
           'Victoza',
           'Alimta',
           'Lotrisone',
           'Avastin',
           'Sovaldi',
           'Gilenya',
           'Epogen',
           'Seroquel',
           'Amaryl',
           'Percocet',
           'SandIMMUNE',
           'Neoral',
           'Lantus',
           'Cialis',
           'Elavil',
           'Vanatrip',
           'Lopid',
           'Flo-Pred',
           'Advil',
           'Aceon',
           'Desyrel',
           'Actos',
           'Proscar',
           'Inbrija',
           'Dopar',
           'Larodopa',
           'Actonel',
           'ProAir',
           'Ventolin',
           'Proventil',
           'Ultram',
           'Sonata',
           'Zebeta',
           'Zovirax',
           'Coumadin',
           'Luvox',
           'Plavix',
           'Vibramycin',
           'Adoxa',
           'Hyzaar',
           'Kytril',
           'Sancuso',
           'Restoril',
           'Prevacid',
           'Augmentin',
           'Mevacor',
           'Altoprev'
           ]

prices = [5,
          65,
          55,
          89,
          80,
          7,
          70,
          15,
          69,
          8,
          20,
          66,
          43,
          34,
          22,
          94,
          87,
          42,
          60,
          34,
          70,
          25,
          100,
          19,
          79,
          58,
          46,
          92,
          23,
          17,
          2,
          79,
          73,
          95,
          24,
          84,
          55,
          76,
          55,
          75,
          84,
          43,
          86,
          27,
          86,
          35,
          18,
          12,
          57,
          86,
          52,
          65,
          66,
          47,
          89,
          38,
          42,
          16,
          49,
          83,
          56,
          10,
          83,
          49,
          8,
          84,
          35,
          95,
          35,
          85,
          93,
          31,
          48,
          57,
          82,
          37,
          47,
          47,
          66,
          45,
          89,
          86,
          92,
          96,
          8,
          26,
          78,
          39,
          46,
          37,
          66,
          75,
          72,
          8,
          52,
          25,
          49,
          101,
          76,
          22,
          74,
          37,
          71,
          64,
          71,
          66,
          66,
          35,
          23,
          6,
          17,
          41,
          79,
          11,
          54,
          85,
          26,
          29,
          14,
          31,
          80,
          88,
          97,
          47,
          97,
          84,
          91,
          2,
          73,
          1,
          10,
          76,
          15,
          23,
          96,
          48,
          61,
          14,
          91,
          38,
          60,
          93,
          55,
          65,
          57,
          32,
          12,
          82,
          19,
          83,
          71,
          99,
          26,
          93,
          36,
          37,
          1,
          90,
          46,
          21,
          4,
          81,
          95,
          60,
          15,
          12,
          89,
          18,
          18,
          39,
          44,
          100,
          17,
          83,
          68,
          68,
          90,
          56,
          15,
          75,
          73,
          61,
          74,
          81,
          20,
          41,
          18,
          73,
          100,
          63,
          8,
          37,
          83,
          44,
          87,
          2,
          43,
          53,
          50,
          72,
          87,
          1,
          27,
          99,
          92,
          3,
          22,
          81,
          80,
          41,
          21,
          37,
          41,
          90,
          96,
          71,
          38,
          57,
          56,
          67,
          59,
          37,
          2,
          61,
          41,
          11,
          28,
          37,
          7,
          55,
          96,
          9]

{
    {
        'name': 'Lexapro',
        'price': 5
    },
    {
        'name': 'Lexapro',
        'price': 5
    },
    {
        'name': 'Lexapro',
        'price': 5
    },
    {
        'name': 'Lexapro',
        'price': 5
    },

}

for num in range(232):
    print(f'd{num} = (name="{TOP_200[num]}"", price={prices[num]})')


#marks = {}.fromkeys('name',[TOP_200])


drug_prices = {'Lexapro': 5,
               'Vicodin': 65,
               'Prinivil': 55,
               'Qbrelis': 89,
               'Zocor': 80,
               'Synthroid': 7,
               'Amoxil': 70,
               'Trimox': 15,
               'Zithromax': 69,
               'Microzide': 8,
               'Aquazide': 20,
               'Norvasc': 66,
               'Xanax': 43,
               'Glucophage': 34,
               'Lipitor': 22,
               'Prilosec': 94,
               'Cipro': 87,
               'Proquin': 42,
               'Zofran': 60,
               'Clozaril': 34,
               'Lasix': 70,
               'Levitra': 25,
               'Sumycin': 100,
               'Ala-Tet': 19,
               'Brodspec': 79,
               'Heparin Sodium': 58,
               'Valcyte': 46,
               'Lamictal': 92,
               'Diflucan': 23,
               'Tenormin': 17,
               'Singulair': 2,
               'Flonase Nasal Spray': 79,
               'Zyloprim': 73,
               'Fosamax': 95,
               'Pepcid': 24,
               'Omnicef': 84,
               'Yaz': 55,
               'Apresoline': 76,
               'Cogentin': 55,
               'Tussionex PennKinetic': 75,
               'Paxil': 84,
               'Ativan': 43,
               'Pyridium': 86,
               'Plaquenil': 27,
               'Lidoderm': 86,
               'Cataflam': 35,
               'Rayos': 18,
               'Deltasone': 12,
               'Zetia': 57,
               'Evista': 86,
               'Dilantin': 52,
               'Lovaza': 65,
               'Zanaflex': 66,
               'Hytrin': 47,
               'Dyrenium': 89,
               'Altace': 38,
               'Pravachol': 42,
               'Risperdal': 16,
               'Lunesta': 49,
               'Celebrex': 83,
               'Premarin': 56,
               'Avelox': 10,
               'Aricept': 83,
               'Macrobid': 49,
               'Macrodantin': 8,
               'Duragesic Skin Patch': 84,
               'Imdur': 35,
               'Prozac': 95,
               'Sarafem': 35,
               'Aristocort': 85,
               'Suboxone': 93,
               'Vyvanse': 31,
               'Pamelor': 48,
               'HumaLOG': 57,
               'Depacon': 82,
               'Depakote': 37,
               'BetaSept': 47,
               'ChloraPrep': 47,
               'Bentyl': 66,
               'Imitrex': 45,
               'Protonix': 89,
               'Lopressor': 86,
               'Robitussen': 92,
               'Valium': 96,
               'Viagra': 8,
               'Bactroban': 26,
               'Januvia': 78,
               'Reglan': 39,
               'Relafen': 46,
               'Keflex': 37,
               'Effexor': 66,
               'Boniva': 75,
               'Zantac': 72,
               'Ex-Lax': 8,
               'Senna Lax': 52,
               'NovoLog': 25,
               'Bayer': 49,
               'Ecotrin': 101,
               'Bufferin': 76,
               'Lioresal': 22,
               'Flagyl': 74,
               'Keppra': 37,
               'Colcrys': 71,
               'Mitigare': 64,
               'Zyprexa': 71,
               'Avodart': 66,
               'TriCor': 66,
               'Antara': 35,
               'Cardura': 23,
               'Aleve': 6,
               'Aldactone': 17,
               'Namenda': 41,
               'Methadose': 79,
               'Vasotec': 11,
               'Epaned': 54,
               'Tamiflu': 85,
               'Requip': 26,
               'PC Pen VK': 29,
               'Pen V': 14,
               'Strattera': 31,
               'Ambien': 80,
               'Advair': 88,
               'Levaquin': 97,
               'Tofranil': 47,
               'Reclast': 97,
               'Zometa': 84,
               'Glucotrol': 91,
               'Constulose': 2,
               'AcipHex': 73,
               'Otrexup': 1,
               'Cleocin': 10,
               'Tylenol': 76,
               'Feosol': 15,
               'Relpax': 23,
               'Carbacot': 96,
               'Robaxin': 48,
               'DiaBeta': 61,
               'Celexa': 14,
               'Benicar': 91,
               'Coreg': 38,
               'Spiriva': 60,
               'Xolair': 93,
               'NitroStat Sublingual': 55,
               'Eliquis': 65,
               'Neurontin': 57,
               'Enbrel': 32,
               'Herceptin': 12,
               'Atripla': 82,
               'Xarelto': 19,
               'Stalevo 50': 83,
               'Fioricet': 71,
               'Levemir': 99,
               'Lovenox': 26,
               'Ritalin': 93,
               'Concerta': 36,
               'Crestor': 37,
               'Xgeva': 1,
               'Prolia': 90,
               'Pradaxa': 46,
               'Sensipar': 21,
               'Vesicare': 4,
               'Haldol': 81,
               'Ala-Cort': 95,
               'HumuLIN': 60,
               'Isentress': 15,
               'Stelara': 12,
               'Mobic': 89,
               'Remicade': 18,
               'Night Time': 18,
               'Renvela': 39,
               'Fragmin': 44,
               'Zoloft': 100,
               'Klonopin': 17,
               'Avalide': 83,
               'Ceftin': 68,
               'Nizoral Topical': 68,
               'Lyrica': 90,
               'Nexium': 56,
               'Combivent Respimat': 15,
               'Niaspan': 75,
               'Uroxatral': 73,
               'Biaxin': 61,
               'Zomig': 74,
               'Invokana': 81,
               'Saxenda': 20,
               'Victoza': 41,
               'Alimta': 18,
               'Lotrisone': 73,
               'Avastin': 100,
               'Sovaldi': 63,
               'Gilenya': 8,
               'Epogen': 37,
               'Seroquel': 83,
               'Amaryl': 44,
               'Percocet': 87,
               'SandIMMUNE': 2,
               'Neoral': 43,
               'Lantus': 53,
               'Cialis': 50,
               'Elavil': 72,
               'Vanatrip': 87,
               'Lopid': 1,
               'Flo-Pred': 27,
               'Advil': 99,
               'Aceon': 92,
               'Desyrel': 3,
               'Actos': 22,
               'Proscar': 81,
               'Inbrija': 80,
               'Dopar': 41,
               'Larodopa': 21,
               'Actonel': 37,
               'ProAir': 41,
               'Ventolin': 90,
               'Proventil': 96,
               'Ultram': 71,
               'Sonata': 38,
               'Zebeta': 57,
               'Zovirax': 56,
               'Coumadin': 67,
               'Luvox': 59,
               'Plavix': 37,
               'Vibramycin': 2,
               'Adoxa': 61,
               'Hyzaar': 41,
               'Kytril': 11,
               'Sancuso': 28,
               'Restoril': 37,
               'Prevacid': 7,
               'Augmentin': 55,
               'Mevacor': 96,
               'Altoprev': 9}
